theme: jekyll-theme-minimal
title: Mon site internet
description: Il va y avoir du boulot pour apprendre à s'en servir, le rendre joli, utiliser git plutôt que github.com et tout le trarlalère ... \n En Avant !
